# Generated by Django 5.2.5 on 2025-08-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(default='ec4c4d07-f290-4e30-b00e-317be13ca809', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.category'),
            preserve_default=False,
        ),
    ]
